apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumb-v2
  labels:
    app: dumb
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dumb
      version: v2
  template:
    metadata:
      labels:
        app: dumb
        version: v2
    spec:
      containers:
      - image: frostmarry/dumbflix-be
        name: dumbplay
        ports:
        - containerPort: 5000
