apiVersion: v1
kind: Service
metadata:
  name: dumb
  labels:
    workload.user.cattle.io/workloadselector: dumbflix
spec:
  ports:
  - name: dumbflix-port
    nodePort: 30163
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    workload.user.cattle.io/workloadselector: dumbflix
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumb-v1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: dumbflix
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: dumbflix
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: dumbflix
    spec:
      containers:
      - env:
        - name: COTE_LOG
          value: "false"
        - name: COTE_LOG_UNKNOWN_EVENTS
          value: "false"
        - name: COTE_REQUEST_TIMEOUT
          value: "300000"
        - name: MICROGEN_SERVICES
          value: main,user
        - name: DISCOVERY_HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
      - image: frostmarry/dumbflix-be
        name: dumbflix
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: 5000tcp01
          protocol: TCP
