apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumbflix
spec:
  selector:
    matchLabels:
      app: dumb
  replicas: 1
  template:
    metadata:
      labels:
        app: dumb
    spec:
      containers:
      - name: dumb
        image: frostmarry/dumbflix-be
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: dumb
  labels:
    app: dumb
spec:
  type: NodePort
  ports:
  - port: 5000    
  selector:
    app: dumb
    tier: dumbflix
